import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './users.routes';
import clientRoutes from './clients.routes';
import meetingRoutes from './meetings.routes';
import strategyRoutes from './strategy.routes';
import summaryRoutes from './summary.routes';
import cohortRoutes from './cohorts.routes';
import editorialRoutes from './editorial.routes';
import briefingRoutes from './briefings.routes';
import sprintRoutes from './sprints.routes';
import whatsappRoutes from './whatsapp.routes';
import reportRoutes from './reports.routes';
import biRoutes from './bi.routes';
import notificationRoutes from './notifications.routes';
import strategicSystemsRoutes from './strategicSystems.routes';
import handoffRoutes from './handoffs.routes';
import coordinatorClientRoutes from './coordinator-clients.routes';
import trioRoutes from './trios.routes';
import sprintSystemRoutes from './sprint.routes';
import commercialRoutes from './commercial.routes';
import knowledgeRoutes from './knowledge.routes';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/clients', clientRoutes);
router.use('/meetings', meetingRoutes);
router.use('/strategy', strategyRoutes);
router.use('/summary', summaryRoutes);
router.use('/cohorts', cohortRoutes);
router.use('/editorial', editorialRoutes);
router.use('/briefings', briefingRoutes);
router.use('/sprints', sprintRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/reports', reportRoutes);
router.use('/bi', biRoutes);
router.use('/notifications', notificationRoutes);
router.use('/systems', strategicSystemsRoutes);
router.use('/handoffs', handoffRoutes);
router.use('/coordinator/clients', coordinatorClientRoutes);
router.use('/trios', trioRoutes);
router.use('/sprint', sprintSystemRoutes);
router.use('/commercial', commercialRoutes);
router.use('/knowledge', knowledgeRoutes);
